# Generated by Django 2.2.1 on 2020-06-09 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='level',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='metapp.Level'),
            preserve_default=False,
        ),
    ]
