# Generated by Django 2.2.1 on 2020-06-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.FileField(upload_to='media/student_pic'),
        ),
    ]
