# Generated by Django 2.2.1 on 2020-06-12 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metapp', '0002_auto_20200611_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackstaff',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metapp.Staff'),
        ),
    ]
