# Generated by Django 3.0.6 on 2023-12-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metapp', '0002_auto_20231222_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.CharField(max_length=100),
        ),
    ]
