# Generated by Django 3.0.6 on 2023-12-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metapp', '0003_auto_20231223_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='staff',
            field=models.TextField(blank=True, null=True),
        ),
    ]
