# Generated by Django 2.2.1 on 2020-06-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metapp', '0003_auto_20200612_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(),
        ),
    ]
