# Generated by Django 3.0.6 on 2023-12-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metapp', '0004_student_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff', models.TextField()),
                ('student', models.TextField()),
                ('report', models.FileField(upload_to='media/reports')),
            ],
        ),
    ]
