# Generated by Django 3.0.6 on 2023-12-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metapp', '0007_auto_20231229_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff', models.TextField()),
                ('student', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('assignment', models.FileField(upload_to='media')),
            ],
        ),
    ]
