# Generated by Django 3.0.6 on 2023-12-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metapp', '0008_assignmentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='media/student_pic'),
        ),
    ]
