# Generated by Django 3.0.6 on 2024-01-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metapp', '0010_invoice_reciepts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff', models.TextField()),
                ('student', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('note', models.FileField(upload_to='media')),
            ],
        ),
    ]
