# Generated by Django 5.0.3 on 2024-03-30 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metapp', '0013_auto_20240106_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='assignment',
            field=models.FileField(upload_to='assignments/'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='assignment',
            field=models.FileField(upload_to='assignment_submission/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice',
            field=models.FileField(upload_to='invoices/'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='note',
            field=models.FileField(upload_to='notes/'),
        ),
        migrations.AlterField(
            model_name='reciepts',
            name='reciept',
            field=models.FileField(upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='report',
            field=models.FileField(upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='profile_pic/staff/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_course_students', to='metapp.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.FileField(upload_to='profile_pic/students/'),
        ),
    ]
