# Generated by Django 5.0.3 on 2024-03-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metapp', '0015_alter_assignments_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='assignment',
            field=models.FileField(upload_to='https://brint-media-bkt-24.s3.amazonaws.com/media/assignments/'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='assignment',
            field=models.FileField(upload_to='https://brint-media-bkt-24.s3.amazonaws.com/media/assignment_submission/'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice',
            field=models.FileField(upload_to='https://brint-media-bkt-24.s3.amazonaws.com/media/invoice/'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='note',
            field=models.FileField(upload_to='https://brint-media-bkt-24.s3.amazonaws.com/media/notes/'),
        ),
        migrations.AlterField(
            model_name='reciepts',
            name='reciept',
            field=models.FileField(upload_to='https://brint-media-bkt-24.s3.amazonaws.com/media/receipt/'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='report',
            field=models.FileField(upload_to='https://brint-media-bkt-24.s3.amazonaws.com/media/reports/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='https://brint-media-bkt-24.s3.amazonaws.com/media//profile-pic/staff/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.FileField(upload_to='https://brint-media-bkt-24.s3.amazonaws.com/media//profile-pic/students/'),
        ),
    ]
