# Generated by Django 5.0.3 on 2024-03-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metapp', '0016_alter_assignments_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice',
            field=models.FileField(upload_to='https://brint-media-bkt-24.s3.amazonaws.com/media//invoices/'),
        ),
    ]
